spring.application.name=07-webflux-demo

# ========== MyBatis-Plus JDBC 数据源 ==========
spring.datasource.url=jdbc:mysql://localhost:3306/reactor_demo?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## ========== R2DBC 响应式数据源（用于 TransactionalOperator 响应式事务） ==========
spring.r2dbc.url=r2dbc:mysql://localhost:3306/reactor_demo?serverTimezone=Asia/Shanghai
spring.r2dbc.username=root
spring.r2dbc.password=root

# ========== MyBatis-Plus 配置 ==========
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.global-config.db-config.logic-delete-field=deleted
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0

# ========== 日志级别 ==========
logging.level.com.kingfish.webflux=debug
