spring.application.name=reactor-transactional-webflux

# ========== R2DBC 响应式数据源 ==========
spring.r2dbc.url=r2dbc:mysql://localhost:3306/reactor_demo?serverTimezone=Asia/Shanghai
spring.r2dbc.username=root
spring.r2dbc.password=root

# ========== 日志级别 ==========
logging.level.com.kingfish.webflux=debug
logging.level.org.springframework.r2dbc=debug
