/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * 购物车表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CartDO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long userId;
    private Long productId;
    private Integer quantity;
    private BigDecimal price;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;
    private Byte deleted;

    public CartDO() {}

    public CartDO(CartDO value) {
        this.id = value.id;
        this.userId = value.userId;
        this.productId = value.productId;
        this.quantity = value.quantity;
        this.price = value.price;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.deleted = value.deleted;
    }

    public CartDO(
        Long id,
        Long userId,
        Long productId,
        Integer quantity,
        BigDecimal price,
        LocalDateTime createTime,
        LocalDateTime updateTime,
        Byte deleted
    ) {
        this.id = id;
        this.userId = userId;
        this.productId = productId;
        this.quantity = quantity;
        this.price = price;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.deleted = deleted;
    }

    /**
     * Getter for <code>reactor_demo.cart.id</code>. 主键ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>reactor_demo.cart.id</code>. 主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>reactor_demo.cart.user_id</code>. 用户ID
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>reactor_demo.cart.user_id</code>. 用户ID
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>reactor_demo.cart.product_id</code>. 商品ID
     */
    public Long getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>reactor_demo.cart.product_id</code>. 商品ID
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * Getter for <code>reactor_demo.cart.quantity</code>. 购买数量
     */
    public Integer getQuantity() {
        return this.quantity;
    }

    /**
     * Setter for <code>reactor_demo.cart.quantity</code>. 购买数量
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * Getter for <code>reactor_demo.cart.price</code>. 加入购物车时的单价
     */
    public BigDecimal getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>reactor_demo.cart.price</code>. 加入购物车时的单价
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * Getter for <code>reactor_demo.cart.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>reactor_demo.cart.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>reactor_demo.cart.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>reactor_demo.cart.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>reactor_demo.cart.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public Byte getDeleted() {
        return this.deleted;
    }

    /**
     * Setter for <code>reactor_demo.cart.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CartDO other = (CartDO) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.productId == null) {
            if (other.productId != null)
                return false;
        }
        else if (!this.productId.equals(other.productId))
            return false;
        if (this.quantity == null) {
            if (other.quantity != null)
                return false;
        }
        else if (!this.quantity.equals(other.quantity))
            return false;
        if (this.price == null) {
            if (other.price != null)
                return false;
        }
        else if (!this.price.equals(other.price))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!this.updateTime.equals(other.updateTime))
            return false;
        if (this.deleted == null) {
            if (other.deleted != null)
                return false;
        }
        else if (!this.deleted.equals(other.deleted))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.productId == null) ? 0 : this.productId.hashCode());
        result = prime * result + ((this.quantity == null) ? 0 : this.quantity.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        result = prime * result + ((this.deleted == null) ? 0 : this.deleted.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CartDO (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(productId);
        sb.append(", ").append(quantity);
        sb.append(", ").append(price);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
