/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * 用户优惠券表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CouponDO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long userId;
    private BigDecimal threshold;
    private BigDecimal discount;
    private Byte status;
    private LocalDateTime expireTime;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;
    private Byte deleted;

    public CouponDO() {}

    public CouponDO(CouponDO value) {
        this.id = value.id;
        this.userId = value.userId;
        this.threshold = value.threshold;
        this.discount = value.discount;
        this.status = value.status;
        this.expireTime = value.expireTime;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.deleted = value.deleted;
    }

    public CouponDO(
        Long id,
        Long userId,
        BigDecimal threshold,
        BigDecimal discount,
        Byte status,
        LocalDateTime expireTime,
        LocalDateTime createTime,
        LocalDateTime updateTime,
        Byte deleted
    ) {
        this.id = id;
        this.userId = userId;
        this.threshold = threshold;
        this.discount = discount;
        this.status = status;
        this.expireTime = expireTime;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.deleted = deleted;
    }

    /**
     * Getter for <code>reactor_demo.coupon.id</code>. 主键ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>reactor_demo.coupon.id</code>. 主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>reactor_demo.coupon.user_id</code>. 用户ID
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>reactor_demo.coupon.user_id</code>. 用户ID
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>reactor_demo.coupon.threshold</code>. 使用门槛（满多少可用）
     */
    public BigDecimal getThreshold() {
        return this.threshold;
    }

    /**
     * Setter for <code>reactor_demo.coupon.threshold</code>. 使用门槛（满多少可用）
     */
    public void setThreshold(BigDecimal threshold) {
        this.threshold = threshold;
    }

    /**
     * Getter for <code>reactor_demo.coupon.discount</code>. 优惠金额
     */
    public BigDecimal getDiscount() {
        return this.discount;
    }

    /**
     * Setter for <code>reactor_demo.coupon.discount</code>. 优惠金额
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * Getter for <code>reactor_demo.coupon.status</code>. 状态 0-未使用 1-已使用 2-已过期
     */
    public Byte getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>reactor_demo.coupon.status</code>. 状态 0-未使用 1-已使用 2-已过期
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * Getter for <code>reactor_demo.coupon.expire_time</code>. 过期时间
     */
    public LocalDateTime getExpireTime() {
        return this.expireTime;
    }

    /**
     * Setter for <code>reactor_demo.coupon.expire_time</code>. 过期时间
     */
    public void setExpireTime(LocalDateTime expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * Getter for <code>reactor_demo.coupon.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>reactor_demo.coupon.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>reactor_demo.coupon.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>reactor_demo.coupon.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>reactor_demo.coupon.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public Byte getDeleted() {
        return this.deleted;
    }

    /**
     * Setter for <code>reactor_demo.coupon.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CouponDO other = (CouponDO) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.threshold == null) {
            if (other.threshold != null)
                return false;
        }
        else if (!this.threshold.equals(other.threshold))
            return false;
        if (this.discount == null) {
            if (other.discount != null)
                return false;
        }
        else if (!this.discount.equals(other.discount))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.expireTime == null) {
            if (other.expireTime != null)
                return false;
        }
        else if (!this.expireTime.equals(other.expireTime))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!this.updateTime.equals(other.updateTime))
            return false;
        if (this.deleted == null) {
            if (other.deleted != null)
                return false;
        }
        else if (!this.deleted.equals(other.deleted))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.threshold == null) ? 0 : this.threshold.hashCode());
        result = prime * result + ((this.discount == null) ? 0 : this.discount.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.expireTime == null) ? 0 : this.expireTime.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        result = prime * result + ((this.deleted == null) ? 0 : this.deleted.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CouponDO (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(threshold);
        sb.append(", ").append(discount);
        sb.append(", ").append(status);
        sb.append(", ").append(expireTime);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
