/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * 会员信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MemberDO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long userId;
    private Integer level;
    private BigDecimal discount;
    private Long totalPoints;
    private LocalDateTime expireTime;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;
    private Byte deleted;

    public MemberDO() {}

    public MemberDO(MemberDO value) {
        this.id = value.id;
        this.userId = value.userId;
        this.level = value.level;
        this.discount = value.discount;
        this.totalPoints = value.totalPoints;
        this.expireTime = value.expireTime;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.deleted = value.deleted;
    }

    public MemberDO(
        Long id,
        Long userId,
        Integer level,
        BigDecimal discount,
        Long totalPoints,
        LocalDateTime expireTime,
        LocalDateTime createTime,
        LocalDateTime updateTime,
        Byte deleted
    ) {
        this.id = id;
        this.userId = userId;
        this.level = level;
        this.discount = discount;
        this.totalPoints = totalPoints;
        this.expireTime = expireTime;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.deleted = deleted;
    }

    /**
     * Getter for <code>reactor_demo.member.id</code>. 主键ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>reactor_demo.member.id</code>. 主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>reactor_demo.member.user_id</code>. 用户ID
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>reactor_demo.member.user_id</code>. 用户ID
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>reactor_demo.member.level</code>. 会员等级
     */
    public Integer getLevel() {
        return this.level;
    }

    /**
     * Setter for <code>reactor_demo.member.level</code>. 会员等级
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * Getter for <code>reactor_demo.member.discount</code>. 折扣率
     */
    public BigDecimal getDiscount() {
        return this.discount;
    }

    /**
     * Setter for <code>reactor_demo.member.discount</code>. 折扣率
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * Getter for <code>reactor_demo.member.total_points</code>. 总积分
     */
    public Long getTotalPoints() {
        return this.totalPoints;
    }

    /**
     * Setter for <code>reactor_demo.member.total_points</code>. 总积分
     */
    public void setTotalPoints(Long totalPoints) {
        this.totalPoints = totalPoints;
    }

    /**
     * Getter for <code>reactor_demo.member.expire_time</code>. 会员过期时间
     */
    public LocalDateTime getExpireTime() {
        return this.expireTime;
    }

    /**
     * Setter for <code>reactor_demo.member.expire_time</code>. 会员过期时间
     */
    public void setExpireTime(LocalDateTime expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * Getter for <code>reactor_demo.member.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>reactor_demo.member.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>reactor_demo.member.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>reactor_demo.member.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>reactor_demo.member.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public Byte getDeleted() {
        return this.deleted;
    }

    /**
     * Setter for <code>reactor_demo.member.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MemberDO other = (MemberDO) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.level == null) {
            if (other.level != null)
                return false;
        }
        else if (!this.level.equals(other.level))
            return false;
        if (this.discount == null) {
            if (other.discount != null)
                return false;
        }
        else if (!this.discount.equals(other.discount))
            return false;
        if (this.totalPoints == null) {
            if (other.totalPoints != null)
                return false;
        }
        else if (!this.totalPoints.equals(other.totalPoints))
            return false;
        if (this.expireTime == null) {
            if (other.expireTime != null)
                return false;
        }
        else if (!this.expireTime.equals(other.expireTime))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!this.updateTime.equals(other.updateTime))
            return false;
        if (this.deleted == null) {
            if (other.deleted != null)
                return false;
        }
        else if (!this.deleted.equals(other.deleted))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.level == null) ? 0 : this.level.hashCode());
        result = prime * result + ((this.discount == null) ? 0 : this.discount.hashCode());
        result = prime * result + ((this.totalPoints == null) ? 0 : this.totalPoints.hashCode());
        result = prime * result + ((this.expireTime == null) ? 0 : this.expireTime.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        result = prime * result + ((this.deleted == null) ? 0 : this.deleted.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MemberDO (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(level);
        sb.append(", ").append(discount);
        sb.append(", ").append(totalPoints);
        sb.append(", ").append(expireTime);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
