/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * 订单主表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderDO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long orderId;
    private Long userId;
    private Long productId;
    private Integer quantity;
    private String orderNo;
    private BigDecimal totalAmount;
    private Byte payStatus;
    private Byte orderStatus;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;
    private Byte deleted;

    public OrderDO() {}

    public OrderDO(OrderDO value) {
        this.id = value.id;
        this.orderId = value.orderId;
        this.userId = value.userId;
        this.productId = value.productId;
        this.quantity = value.quantity;
        this.orderNo = value.orderNo;
        this.totalAmount = value.totalAmount;
        this.payStatus = value.payStatus;
        this.orderStatus = value.orderStatus;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.deleted = value.deleted;
    }

    public OrderDO(
        Long id,
        Long orderId,
        Long userId,
        Long productId,
        Integer quantity,
        String orderNo,
        BigDecimal totalAmount,
        Byte payStatus,
        Byte orderStatus,
        LocalDateTime createTime,
        LocalDateTime updateTime,
        Byte deleted
    ) {
        this.id = id;
        this.orderId = orderId;
        this.userId = userId;
        this.productId = productId;
        this.quantity = quantity;
        this.orderNo = orderNo;
        this.totalAmount = totalAmount;
        this.payStatus = payStatus;
        this.orderStatus = orderStatus;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.deleted = deleted;
    }

    /**
     * Getter for <code>reactor_demo.order.id</code>. 主键ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>reactor_demo.order.id</code>. 主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>reactor_demo.order.order_id</code>. 订单ID
     */
    public Long getOrderId() {
        return this.orderId;
    }

    /**
     * Setter for <code>reactor_demo.order.order_id</code>. 订单ID
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * Getter for <code>reactor_demo.order.user_id</code>. 用户ID
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>reactor_demo.order.user_id</code>. 用户ID
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>reactor_demo.order.product_id</code>. 商品ID
     */
    public Long getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>reactor_demo.order.product_id</code>. 商品ID
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * Getter for <code>reactor_demo.order.quantity</code>. 商品数量
     */
    public Integer getQuantity() {
        return this.quantity;
    }

    /**
     * Setter for <code>reactor_demo.order.quantity</code>. 商品数量
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * Getter for <code>reactor_demo.order.order_no</code>. 订单编号
     */
    public String getOrderNo() {
        return this.orderNo;
    }

    /**
     * Setter for <code>reactor_demo.order.order_no</code>. 订单编号
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * Getter for <code>reactor_demo.order.total_amount</code>. 订单总金额
     */
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }

    /**
     * Setter for <code>reactor_demo.order.total_amount</code>. 订单总金额
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * Getter for <code>reactor_demo.order.pay_status</code>. 支付状态 0-未支付 1-已支付
     */
    public Byte getPayStatus() {
        return this.payStatus;
    }

    /**
     * Setter for <code>reactor_demo.order.pay_status</code>. 支付状态 0-未支付 1-已支付
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * Getter for <code>reactor_demo.order.order_status</code>. 订单状态 0-待付款 1-待发货
     * 2-待收货 3-已完成 4-已取消
     */
    public Byte getOrderStatus() {
        return this.orderStatus;
    }

    /**
     * Setter for <code>reactor_demo.order.order_status</code>. 订单状态 0-待付款 1-待发货
     * 2-待收货 3-已完成 4-已取消
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * Getter for <code>reactor_demo.order.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>reactor_demo.order.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>reactor_demo.order.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>reactor_demo.order.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>reactor_demo.order.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public Byte getDeleted() {
        return this.deleted;
    }

    /**
     * Setter for <code>reactor_demo.order.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OrderDO other = (OrderDO) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.orderId == null) {
            if (other.orderId != null)
                return false;
        }
        else if (!this.orderId.equals(other.orderId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.productId == null) {
            if (other.productId != null)
                return false;
        }
        else if (!this.productId.equals(other.productId))
            return false;
        if (this.quantity == null) {
            if (other.quantity != null)
                return false;
        }
        else if (!this.quantity.equals(other.quantity))
            return false;
        if (this.orderNo == null) {
            if (other.orderNo != null)
                return false;
        }
        else if (!this.orderNo.equals(other.orderNo))
            return false;
        if (this.totalAmount == null) {
            if (other.totalAmount != null)
                return false;
        }
        else if (!this.totalAmount.equals(other.totalAmount))
            return false;
        if (this.payStatus == null) {
            if (other.payStatus != null)
                return false;
        }
        else if (!this.payStatus.equals(other.payStatus))
            return false;
        if (this.orderStatus == null) {
            if (other.orderStatus != null)
                return false;
        }
        else if (!this.orderStatus.equals(other.orderStatus))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!this.updateTime.equals(other.updateTime))
            return false;
        if (this.deleted == null) {
            if (other.deleted != null)
                return false;
        }
        else if (!this.deleted.equals(other.deleted))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.orderId == null) ? 0 : this.orderId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.productId == null) ? 0 : this.productId.hashCode());
        result = prime * result + ((this.quantity == null) ? 0 : this.quantity.hashCode());
        result = prime * result + ((this.orderNo == null) ? 0 : this.orderNo.hashCode());
        result = prime * result + ((this.totalAmount == null) ? 0 : this.totalAmount.hashCode());
        result = prime * result + ((this.payStatus == null) ? 0 : this.payStatus.hashCode());
        result = prime * result + ((this.orderStatus == null) ? 0 : this.orderStatus.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        result = prime * result + ((this.deleted == null) ? 0 : this.deleted.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrderDO (");

        sb.append(id);
        sb.append(", ").append(orderId);
        sb.append(", ").append(userId);
        sb.append(", ").append(productId);
        sb.append(", ").append(quantity);
        sb.append(", ").append(orderNo);
        sb.append(", ").append(totalAmount);
        sb.append(", ").append(payStatus);
        sb.append(", ").append(orderStatus);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
