/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 订单物流信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderLogisticsDO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long logisticsId;
    private Long orderId;
    private String company;
    private String logisticsNo;
    private String status;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;
    private Byte deleted;

    public OrderLogisticsDO() {}

    public OrderLogisticsDO(OrderLogisticsDO value) {
        this.id = value.id;
        this.logisticsId = value.logisticsId;
        this.orderId = value.orderId;
        this.company = value.company;
        this.logisticsNo = value.logisticsNo;
        this.status = value.status;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.deleted = value.deleted;
    }

    public OrderLogisticsDO(
        Long id,
        Long logisticsId,
        Long orderId,
        String company,
        String logisticsNo,
        String status,
        LocalDateTime createTime,
        LocalDateTime updateTime,
        Byte deleted
    ) {
        this.id = id;
        this.logisticsId = logisticsId;
        this.orderId = orderId;
        this.company = company;
        this.logisticsNo = logisticsNo;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.deleted = deleted;
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.id</code>. 主键ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>reactor_demo.order_logistics.id</code>. 主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.logistics_id</code>. 物流ID
     */
    public Long getLogisticsId() {
        return this.logisticsId;
    }

    /**
     * Setter for <code>reactor_demo.order_logistics.logistics_id</code>. 物流ID
     */
    public void setLogisticsId(Long logisticsId) {
        this.logisticsId = logisticsId;
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.order_id</code>. 订单ID
     */
    public Long getOrderId() {
        return this.orderId;
    }

    /**
     * Setter for <code>reactor_demo.order_logistics.order_id</code>. 订单ID
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.company</code>. 物流公司
     */
    public String getCompany() {
        return this.company;
    }

    /**
     * Setter for <code>reactor_demo.order_logistics.company</code>. 物流公司
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.logistics_no</code>. 物流单号
     */
    public String getLogisticsNo() {
        return this.logisticsNo;
    }

    /**
     * Setter for <code>reactor_demo.order_logistics.logistics_no</code>. 物流单号
     */
    public void setLogisticsNo(String logisticsNo) {
        this.logisticsNo = logisticsNo;
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.status</code>. 物流状态
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>reactor_demo.order_logistics.status</code>. 物流状态
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>reactor_demo.order_logistics.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>reactor_demo.order_logistics.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.deleted</code>. 删除标记 0-未删除
     * 1-已删除
     */
    public Byte getDeleted() {
        return this.deleted;
    }

    /**
     * Setter for <code>reactor_demo.order_logistics.deleted</code>. 删除标记 0-未删除
     * 1-已删除
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OrderLogisticsDO other = (OrderLogisticsDO) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.logisticsId == null) {
            if (other.logisticsId != null)
                return false;
        }
        else if (!this.logisticsId.equals(other.logisticsId))
            return false;
        if (this.orderId == null) {
            if (other.orderId != null)
                return false;
        }
        else if (!this.orderId.equals(other.orderId))
            return false;
        if (this.company == null) {
            if (other.company != null)
                return false;
        }
        else if (!this.company.equals(other.company))
            return false;
        if (this.logisticsNo == null) {
            if (other.logisticsNo != null)
                return false;
        }
        else if (!this.logisticsNo.equals(other.logisticsNo))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!this.updateTime.equals(other.updateTime))
            return false;
        if (this.deleted == null) {
            if (other.deleted != null)
                return false;
        }
        else if (!this.deleted.equals(other.deleted))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.logisticsId == null) ? 0 : this.logisticsId.hashCode());
        result = prime * result + ((this.orderId == null) ? 0 : this.orderId.hashCode());
        result = prime * result + ((this.company == null) ? 0 : this.company.hashCode());
        result = prime * result + ((this.logisticsNo == null) ? 0 : this.logisticsNo.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        result = prime * result + ((this.deleted == null) ? 0 : this.deleted.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrderLogisticsDO (");

        sb.append(id);
        sb.append(", ").append(logisticsId);
        sb.append(", ").append(orderId);
        sb.append(", ").append(company);
        sb.append(", ").append(logisticsNo);
        sb.append(", ").append(status);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
