/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * 商品表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductDO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long productId;
    private String productName;
    private BigDecimal price;
    private Integer stock;
    private Byte status;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;
    private Byte deleted;

    public ProductDO() {}

    public ProductDO(ProductDO value) {
        this.id = value.id;
        this.productId = value.productId;
        this.productName = value.productName;
        this.price = value.price;
        this.stock = value.stock;
        this.status = value.status;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.deleted = value.deleted;
    }

    public ProductDO(
        Long id,
        Long productId,
        String productName,
        BigDecimal price,
        Integer stock,
        Byte status,
        LocalDateTime createTime,
        LocalDateTime updateTime,
        Byte deleted
    ) {
        this.id = id;
        this.productId = productId;
        this.productName = productName;
        this.price = price;
        this.stock = stock;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.deleted = deleted;
    }

    /**
     * Getter for <code>reactor_demo.product.id</code>. 主键ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>reactor_demo.product.id</code>. 主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>reactor_demo.product.product_id</code>. 商品ID
     */
    public Long getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>reactor_demo.product.product_id</code>. 商品ID
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * Getter for <code>reactor_demo.product.product_name</code>. 商品名称
     */
    public String getProductName() {
        return this.productName;
    }

    /**
     * Setter for <code>reactor_demo.product.product_name</code>. 商品名称
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * Getter for <code>reactor_demo.product.price</code>. 销售价格
     */
    public BigDecimal getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>reactor_demo.product.price</code>. 销售价格
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * Getter for <code>reactor_demo.product.stock</code>. 库存数量
     */
    public Integer getStock() {
        return this.stock;
    }

    /**
     * Setter for <code>reactor_demo.product.stock</code>. 库存数量
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * Getter for <code>reactor_demo.product.status</code>. 商品状态 0-下架 1-上架
     */
    public Byte getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>reactor_demo.product.status</code>. 商品状态 0-下架 1-上架
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * Getter for <code>reactor_demo.product.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>reactor_demo.product.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>reactor_demo.product.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>reactor_demo.product.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>reactor_demo.product.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public Byte getDeleted() {
        return this.deleted;
    }

    /**
     * Setter for <code>reactor_demo.product.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ProductDO other = (ProductDO) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.productId == null) {
            if (other.productId != null)
                return false;
        }
        else if (!this.productId.equals(other.productId))
            return false;
        if (this.productName == null) {
            if (other.productName != null)
                return false;
        }
        else if (!this.productName.equals(other.productName))
            return false;
        if (this.price == null) {
            if (other.price != null)
                return false;
        }
        else if (!this.price.equals(other.price))
            return false;
        if (this.stock == null) {
            if (other.stock != null)
                return false;
        }
        else if (!this.stock.equals(other.stock))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!this.updateTime.equals(other.updateTime))
            return false;
        if (this.deleted == null) {
            if (other.deleted != null)
                return false;
        }
        else if (!this.deleted.equals(other.deleted))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.productId == null) ? 0 : this.productId.hashCode());
        result = prime * result + ((this.productName == null) ? 0 : this.productName.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.stock == null) ? 0 : this.stock.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        result = prime * result + ((this.deleted == null) ? 0 : this.deleted.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductDO (");

        sb.append(id);
        sb.append(", ").append(productId);
        sb.append(", ").append(productName);
        sb.append(", ").append(price);
        sb.append(", ").append(stock);
        sb.append(", ").append(status);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
