/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 用户收货地址表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserAddressDO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long addressId;
    private Long userId;
    private String receiver;
    private String phone;
    private String province;
    private String city;
    private String detail;
    private Byte isDefault;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;
    private Byte deleted;

    public UserAddressDO() {}

    public UserAddressDO(UserAddressDO value) {
        this.id = value.id;
        this.addressId = value.addressId;
        this.userId = value.userId;
        this.receiver = value.receiver;
        this.phone = value.phone;
        this.province = value.province;
        this.city = value.city;
        this.detail = value.detail;
        this.isDefault = value.isDefault;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.deleted = value.deleted;
    }

    public UserAddressDO(
        Long id,
        Long addressId,
        Long userId,
        String receiver,
        String phone,
        String province,
        String city,
        String detail,
        Byte isDefault,
        LocalDateTime createTime,
        LocalDateTime updateTime,
        Byte deleted
    ) {
        this.id = id;
        this.addressId = addressId;
        this.userId = userId;
        this.receiver = receiver;
        this.phone = phone;
        this.province = province;
        this.city = city;
        this.detail = detail;
        this.isDefault = isDefault;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.deleted = deleted;
    }

    /**
     * Getter for <code>reactor_demo.user_address.id</code>. 主键ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>reactor_demo.user_address.id</code>. 主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>reactor_demo.user_address.address_id</code>. 地址ID
     */
    public Long getAddressId() {
        return this.addressId;
    }

    /**
     * Setter for <code>reactor_demo.user_address.address_id</code>. 地址ID
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * Getter for <code>reactor_demo.user_address.user_id</code>. 用户ID
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>reactor_demo.user_address.user_id</code>. 用户ID
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>reactor_demo.user_address.receiver</code>. 收件人姓名
     */
    public String getReceiver() {
        return this.receiver;
    }

    /**
     * Setter for <code>reactor_demo.user_address.receiver</code>. 收件人姓名
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /**
     * Getter for <code>reactor_demo.user_address.phone</code>. 收件人电话
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>reactor_demo.user_address.phone</code>. 收件人电话
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Getter for <code>reactor_demo.user_address.province</code>. 省份
     */
    public String getProvince() {
        return this.province;
    }

    /**
     * Setter for <code>reactor_demo.user_address.province</code>. 省份
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * Getter for <code>reactor_demo.user_address.city</code>. 城市
     */
    public String getCity() {
        return this.city;
    }

    /**
     * Setter for <code>reactor_demo.user_address.city</code>. 城市
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for <code>reactor_demo.user_address.detail</code>. 详细地址
     */
    public String getDetail() {
        return this.detail;
    }

    /**
     * Setter for <code>reactor_demo.user_address.detail</code>. 详细地址
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * Getter for <code>reactor_demo.user_address.is_default</code>. 是否默认地址 0-否
     * 1-是
     */
    public Byte getIsDefault() {
        return this.isDefault;
    }

    /**
     * Setter for <code>reactor_demo.user_address.is_default</code>. 是否默认地址 0-否
     * 1-是
     */
    public void setIsDefault(Byte isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * Getter for <code>reactor_demo.user_address.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>reactor_demo.user_address.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>reactor_demo.user_address.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>reactor_demo.user_address.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>reactor_demo.user_address.deleted</code>. 删除标记 0-未删除
     * 1-已删除
     */
    public Byte getDeleted() {
        return this.deleted;
    }

    /**
     * Setter for <code>reactor_demo.user_address.deleted</code>. 删除标记 0-未删除
     * 1-已删除
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserAddressDO other = (UserAddressDO) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.addressId == null) {
            if (other.addressId != null)
                return false;
        }
        else if (!this.addressId.equals(other.addressId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.receiver == null) {
            if (other.receiver != null)
                return false;
        }
        else if (!this.receiver.equals(other.receiver))
            return false;
        if (this.phone == null) {
            if (other.phone != null)
                return false;
        }
        else if (!this.phone.equals(other.phone))
            return false;
        if (this.province == null) {
            if (other.province != null)
                return false;
        }
        else if (!this.province.equals(other.province))
            return false;
        if (this.city == null) {
            if (other.city != null)
                return false;
        }
        else if (!this.city.equals(other.city))
            return false;
        if (this.detail == null) {
            if (other.detail != null)
                return false;
        }
        else if (!this.detail.equals(other.detail))
            return false;
        if (this.isDefault == null) {
            if (other.isDefault != null)
                return false;
        }
        else if (!this.isDefault.equals(other.isDefault))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!this.updateTime.equals(other.updateTime))
            return false;
        if (this.deleted == null) {
            if (other.deleted != null)
                return false;
        }
        else if (!this.deleted.equals(other.deleted))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.addressId == null) ? 0 : this.addressId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.receiver == null) ? 0 : this.receiver.hashCode());
        result = prime * result + ((this.phone == null) ? 0 : this.phone.hashCode());
        result = prime * result + ((this.province == null) ? 0 : this.province.hashCode());
        result = prime * result + ((this.city == null) ? 0 : this.city.hashCode());
        result = prime * result + ((this.detail == null) ? 0 : this.detail.hashCode());
        result = prime * result + ((this.isDefault == null) ? 0 : this.isDefault.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        result = prime * result + ((this.deleted == null) ? 0 : this.deleted.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserAddressDO (");

        sb.append(id);
        sb.append(", ").append(addressId);
        sb.append(", ").append(userId);
        sb.append(", ").append(receiver);
        sb.append(", ").append(phone);
        sb.append(", ").append(province);
        sb.append(", ").append(city);
        sb.append(", ").append(detail);
        sb.append(", ").append(isDefault);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
