/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 用户消息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserMessageDO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long msgId;
    private Long userId;
    private String title;
    private String content;
    private Byte isRead;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;
    private Byte deleted;

    public UserMessageDO() {}

    public UserMessageDO(UserMessageDO value) {
        this.id = value.id;
        this.msgId = value.msgId;
        this.userId = value.userId;
        this.title = value.title;
        this.content = value.content;
        this.isRead = value.isRead;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.deleted = value.deleted;
    }

    public UserMessageDO(
        Long id,
        Long msgId,
        Long userId,
        String title,
        String content,
        Byte isRead,
        LocalDateTime createTime,
        LocalDateTime updateTime,
        Byte deleted
    ) {
        this.id = id;
        this.msgId = msgId;
        this.userId = userId;
        this.title = title;
        this.content = content;
        this.isRead = isRead;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.deleted = deleted;
    }

    /**
     * Getter for <code>reactor_demo.user_message.id</code>. 主键ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>reactor_demo.user_message.id</code>. 主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>reactor_demo.user_message.msg_id</code>. 消息ID
     */
    public Long getMsgId() {
        return this.msgId;
    }

    /**
     * Setter for <code>reactor_demo.user_message.msg_id</code>. 消息ID
     */
    public void setMsgId(Long msgId) {
        this.msgId = msgId;
    }

    /**
     * Getter for <code>reactor_demo.user_message.user_id</code>. 用户ID
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>reactor_demo.user_message.user_id</code>. 用户ID
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>reactor_demo.user_message.title</code>. 消息标题
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>reactor_demo.user_message.title</code>. 消息标题
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>reactor_demo.user_message.content</code>. 消息内容
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>reactor_demo.user_message.content</code>. 消息内容
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Getter for <code>reactor_demo.user_message.is_read</code>. 是否已读 0-未读 1-已读
     */
    public Byte getIsRead() {
        return this.isRead;
    }

    /**
     * Setter for <code>reactor_demo.user_message.is_read</code>. 是否已读 0-未读 1-已读
     */
    public void setIsRead(Byte isRead) {
        this.isRead = isRead;
    }

    /**
     * Getter for <code>reactor_demo.user_message.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>reactor_demo.user_message.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>reactor_demo.user_message.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>reactor_demo.user_message.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>reactor_demo.user_message.deleted</code>. 删除标记 0-未删除
     * 1-已删除
     */
    public Byte getDeleted() {
        return this.deleted;
    }

    /**
     * Setter for <code>reactor_demo.user_message.deleted</code>. 删除标记 0-未删除
     * 1-已删除
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserMessageDO other = (UserMessageDO) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.msgId == null) {
            if (other.msgId != null)
                return false;
        }
        else if (!this.msgId.equals(other.msgId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.content == null) {
            if (other.content != null)
                return false;
        }
        else if (!this.content.equals(other.content))
            return false;
        if (this.isRead == null) {
            if (other.isRead != null)
                return false;
        }
        else if (!this.isRead.equals(other.isRead))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!this.updateTime.equals(other.updateTime))
            return false;
        if (this.deleted == null) {
            if (other.deleted != null)
                return false;
        }
        else if (!this.deleted.equals(other.deleted))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.msgId == null) ? 0 : this.msgId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        result = prime * result + ((this.isRead == null) ? 0 : this.isRead.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        result = prime * result + ((this.deleted == null) ? 0 : this.deleted.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserMessageDO (");

        sb.append(id);
        sb.append(", ").append(msgId);
        sb.append(", ").append(userId);
        sb.append(", ").append(title);
        sb.append(", ").append(content);
        sb.append(", ").append(isRead);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
