/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 用户扩展信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserExtDO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long userId;
    private String realName;
    private String idCard;
    private String phone;
    private String email;
    private Byte sex;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;
    private Byte deleted;

    public UserExtDO() {}

    public UserExtDO(UserExtDO value) {
        this.id = value.id;
        this.userId = value.userId;
        this.realName = value.realName;
        this.idCard = value.idCard;
        this.phone = value.phone;
        this.email = value.email;
        this.sex = value.sex;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.deleted = value.deleted;
    }

    public UserExtDO(
        Long id,
        Long userId,
        String realName,
        String idCard,
        String phone,
        String email,
        Byte sex,
        LocalDateTime createTime,
        LocalDateTime updateTime,
        Byte deleted
    ) {
        this.id = id;
        this.userId = userId;
        this.realName = realName;
        this.idCard = idCard;
        this.phone = phone;
        this.email = email;
        this.sex = sex;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.deleted = deleted;
    }

    /**
     * Getter for <code>reactor_demo.user_ext.id</code>. 主键ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>reactor_demo.user_ext.id</code>. 主键ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>reactor_demo.user_ext.user_id</code>. 用户ID
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>reactor_demo.user_ext.user_id</code>. 用户ID
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>reactor_demo.user_ext.real_name</code>. 真实姓名
     */
    public String getRealName() {
        return this.realName;
    }

    /**
     * Setter for <code>reactor_demo.user_ext.real_name</code>. 真实姓名
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * Getter for <code>reactor_demo.user_ext.id_card</code>. 身份证号
     */
    public String getIdCard() {
        return this.idCard;
    }

    /**
     * Setter for <code>reactor_demo.user_ext.id_card</code>. 身份证号
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * Getter for <code>reactor_demo.user_ext.phone</code>. 手机号
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>reactor_demo.user_ext.phone</code>. 手机号
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Getter for <code>reactor_demo.user_ext.email</code>. 邮箱
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>reactor_demo.user_ext.email</code>. 邮箱
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>reactor_demo.user_ext.sex</code>. 性别 0-未知 1-男 2-女
     */
    public Byte getSex() {
        return this.sex;
    }

    /**
     * Setter for <code>reactor_demo.user_ext.sex</code>. 性别 0-未知 1-男 2-女
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * Getter for <code>reactor_demo.user_ext.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>reactor_demo.user_ext.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>reactor_demo.user_ext.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>reactor_demo.user_ext.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>reactor_demo.user_ext.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public Byte getDeleted() {
        return this.deleted;
    }

    /**
     * Setter for <code>reactor_demo.user_ext.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserExtDO other = (UserExtDO) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.realName == null) {
            if (other.realName != null)
                return false;
        }
        else if (!this.realName.equals(other.realName))
            return false;
        if (this.idCard == null) {
            if (other.idCard != null)
                return false;
        }
        else if (!this.idCard.equals(other.idCard))
            return false;
        if (this.phone == null) {
            if (other.phone != null)
                return false;
        }
        else if (!this.phone.equals(other.phone))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.sex == null) {
            if (other.sex != null)
                return false;
        }
        else if (!this.sex.equals(other.sex))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!this.updateTime.equals(other.updateTime))
            return false;
        if (this.deleted == null) {
            if (other.deleted != null)
                return false;
        }
        else if (!this.deleted.equals(other.deleted))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.realName == null) ? 0 : this.realName.hashCode());
        result = prime * result + ((this.idCard == null) ? 0 : this.idCard.hashCode());
        result = prime * result + ((this.phone == null) ? 0 : this.phone.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.sex == null) ? 0 : this.sex.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        result = prime * result + ((this.deleted == null) ? 0 : this.deleted.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserExtDO (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(realName);
        sb.append(", ").append(idCard);
        sb.append(", ").append(phone);
        sb.append(", ").append(email);
        sb.append(", ").append(sex);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
