/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq;


import com.kingfish.reactor.domain.model.jooq.tables.Cart;
import com.kingfish.reactor.domain.model.jooq.tables.Coupon;
import com.kingfish.reactor.domain.model.jooq.tables.Order;
import com.kingfish.reactor.domain.model.jooq.tables.OrderLogistics;
import com.kingfish.reactor.domain.model.jooq.tables.UserAddress;
import com.kingfish.reactor.domain.model.jooq.tables.UserMessage;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in reactor_demo.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ORDER_LOGISTICS_IDX_ORDER_ID = Internal.createIndex(DSL.name("idx_order_id"), OrderLogistics.ORDER_LOGISTICS, new OrderField[] { OrderLogistics.ORDER_LOGISTICS.ORDER_ID }, false);
    public static final Index CART_IDX_USER_ID = Internal.createIndex(DSL.name("idx_user_id"), Cart.CART, new OrderField[] { Cart.CART.USER_ID }, false);
    public static final Index COUPON_IDX_USER_ID = Internal.createIndex(DSL.name("idx_user_id"), Coupon.COUPON, new OrderField[] { Coupon.COUPON.USER_ID }, false);
    public static final Index ORDER_IDX_USER_ID = Internal.createIndex(DSL.name("idx_user_id"), Order.ORDER, new OrderField[] { Order.ORDER.USER_ID }, false);
    public static final Index USER_ADDRESS_IDX_USER_ID = Internal.createIndex(DSL.name("idx_user_id"), UserAddress.USER_ADDRESS, new OrderField[] { UserAddress.USER_ADDRESS.USER_ID }, false);
    public static final Index USER_MESSAGE_IDX_USER_ID = Internal.createIndex(DSL.name("idx_user_id"), UserMessage.USER_MESSAGE, new OrderField[] { UserMessage.USER_MESSAGE.USER_ID }, false);
}
