/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq;


import com.kingfish.reactor.domain.model.jooq.tables.Cart;
import com.kingfish.reactor.domain.model.jooq.tables.Coupon;
import com.kingfish.reactor.domain.model.jooq.tables.Member;
import com.kingfish.reactor.domain.model.jooq.tables.Order;
import com.kingfish.reactor.domain.model.jooq.tables.OrderLogistics;
import com.kingfish.reactor.domain.model.jooq.tables.Product;
import com.kingfish.reactor.domain.model.jooq.tables.User;
import com.kingfish.reactor.domain.model.jooq.tables.UserAddress;
import com.kingfish.reactor.domain.model.jooq.tables.UserExt;
import com.kingfish.reactor.domain.model.jooq.tables.UserMessage;
import com.kingfish.reactor.domain.model.jooq.tables.records.CartRecord;
import com.kingfish.reactor.domain.model.jooq.tables.records.CouponRecord;
import com.kingfish.reactor.domain.model.jooq.tables.records.MemberRecord;
import com.kingfish.reactor.domain.model.jooq.tables.records.OrderLogisticsRecord;
import com.kingfish.reactor.domain.model.jooq.tables.records.OrderRecord;
import com.kingfish.reactor.domain.model.jooq.tables.records.ProductRecord;
import com.kingfish.reactor.domain.model.jooq.tables.records.UserAddressRecord;
import com.kingfish.reactor.domain.model.jooq.tables.records.UserExtRecord;
import com.kingfish.reactor.domain.model.jooq.tables.records.UserMessageRecord;
import com.kingfish.reactor.domain.model.jooq.tables.records.UserRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * reactor_demo.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CartRecord> KEY_CART_PRIMARY = Internal.createUniqueKey(Cart.CART, DSL.name("KEY_cart_PRIMARY"), new TableField[] { Cart.CART.ID }, true);
    public static final UniqueKey<CouponRecord> KEY_COUPON_PRIMARY = Internal.createUniqueKey(Coupon.COUPON, DSL.name("KEY_coupon_PRIMARY"), new TableField[] { Coupon.COUPON.ID }, true);
    public static final UniqueKey<MemberRecord> KEY_MEMBER_PRIMARY = Internal.createUniqueKey(Member.MEMBER, DSL.name("KEY_member_PRIMARY"), new TableField[] { Member.MEMBER.ID }, true);
    public static final UniqueKey<MemberRecord> KEY_MEMBER_UK_USER_ID = Internal.createUniqueKey(Member.MEMBER, DSL.name("KEY_member_uk_user_id"), new TableField[] { Member.MEMBER.USER_ID }, true);
    public static final UniqueKey<OrderRecord> KEY_ORDER_PRIMARY = Internal.createUniqueKey(Order.ORDER, DSL.name("KEY_order_PRIMARY"), new TableField[] { Order.ORDER.ID }, true);
    public static final UniqueKey<OrderRecord> KEY_ORDER_UK_ORDER_ID = Internal.createUniqueKey(Order.ORDER, DSL.name("KEY_order_uk_order_id"), new TableField[] { Order.ORDER.ORDER_ID }, true);
    public static final UniqueKey<OrderLogisticsRecord> KEY_ORDER_LOGISTICS_PRIMARY = Internal.createUniqueKey(OrderLogistics.ORDER_LOGISTICS, DSL.name("KEY_order_logistics_PRIMARY"), new TableField[] { OrderLogistics.ORDER_LOGISTICS.ID }, true);
    public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = Internal.createUniqueKey(Product.PRODUCT, DSL.name("KEY_product_PRIMARY"), new TableField[] { Product.PRODUCT.ID }, true);
    public static final UniqueKey<ProductRecord> KEY_PRODUCT_UK_PRODUCT_ID = Internal.createUniqueKey(Product.PRODUCT, DSL.name("KEY_product_uk_product_id"), new TableField[] { Product.PRODUCT.PRODUCT_ID }, true);
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_PRIMARY"), new TableField[] { User.USER.ID }, true);
    public static final UniqueKey<UserAddressRecord> KEY_USER_ADDRESS_PRIMARY = Internal.createUniqueKey(UserAddress.USER_ADDRESS, DSL.name("KEY_user_address_PRIMARY"), new TableField[] { UserAddress.USER_ADDRESS.ID }, true);
    public static final UniqueKey<UserExtRecord> KEY_USER_EXT_PRIMARY = Internal.createUniqueKey(UserExt.USER_EXT, DSL.name("KEY_user_ext_PRIMARY"), new TableField[] { UserExt.USER_EXT.ID }, true);
    public static final UniqueKey<UserExtRecord> KEY_USER_EXT_UK_USER_ID = Internal.createUniqueKey(UserExt.USER_EXT, DSL.name("KEY_user_ext_uk_user_id"), new TableField[] { UserExt.USER_EXT.USER_ID }, true);
    public static final UniqueKey<UserMessageRecord> KEY_USER_MESSAGE_PRIMARY = Internal.createUniqueKey(UserMessage.USER_MESSAGE, DSL.name("KEY_user_message_PRIMARY"), new TableField[] { UserMessage.USER_MESSAGE.ID }, true);
}
