/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq;


import com.kingfish.reactor.domain.model.jooq.tables.Cart;
import com.kingfish.reactor.domain.model.jooq.tables.Coupon;
import com.kingfish.reactor.domain.model.jooq.tables.Member;
import com.kingfish.reactor.domain.model.jooq.tables.Order;
import com.kingfish.reactor.domain.model.jooq.tables.OrderLogistics;
import com.kingfish.reactor.domain.model.jooq.tables.Product;
import com.kingfish.reactor.domain.model.jooq.tables.User;
import com.kingfish.reactor.domain.model.jooq.tables.UserAddress;
import com.kingfish.reactor.domain.model.jooq.tables.UserExt;
import com.kingfish.reactor.domain.model.jooq.tables.UserMessage;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReactorDemo extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reactor_demo</code>
     */
    public static final ReactorDemo REACTOR_DEMO = new ReactorDemo();

    /**
     * 购物车表
     */
    public final Cart CART = Cart.CART;

    /**
     * 用户优惠券表
     */
    public final Coupon COUPON = Coupon.COUPON;

    /**
     * 会员信息表
     */
    public final Member MEMBER = Member.MEMBER;

    /**
     * 订单主表
     */
    public final Order ORDER = Order.ORDER;

    /**
     * 订单物流信息表
     */
    public final OrderLogistics ORDER_LOGISTICS = OrderLogistics.ORDER_LOGISTICS;

    /**
     * 商品表
     */
    public final Product PRODUCT = Product.PRODUCT;

    /**
     * 用户基础信息表
     */
    public final User USER = User.USER;

    /**
     * 用户收货地址表
     */
    public final UserAddress USER_ADDRESS = UserAddress.USER_ADDRESS;

    /**
     * 用户扩展信息表
     */
    public final UserExt USER_EXT = UserExt.USER_EXT;

    /**
     * 用户消息表
     */
    public final UserMessage USER_MESSAGE = UserMessage.USER_MESSAGE;

    /**
     * No further instances allowed
     */
    private ReactorDemo() {
        super("reactor_demo", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Cart.CART,
            Coupon.COUPON,
            Member.MEMBER,
            Order.ORDER,
            OrderLogistics.ORDER_LOGISTICS,
            Product.PRODUCT,
            User.USER,
            UserAddress.USER_ADDRESS,
            UserExt.USER_EXT,
            UserMessage.USER_MESSAGE
        );
    }
}
