/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq;


import com.kingfish.reactor.domain.model.jooq.tables.Cart;
import com.kingfish.reactor.domain.model.jooq.tables.Coupon;
import com.kingfish.reactor.domain.model.jooq.tables.Member;
import com.kingfish.reactor.domain.model.jooq.tables.Order;
import com.kingfish.reactor.domain.model.jooq.tables.OrderLogistics;
import com.kingfish.reactor.domain.model.jooq.tables.Product;
import com.kingfish.reactor.domain.model.jooq.tables.User;
import com.kingfish.reactor.domain.model.jooq.tables.UserAddress;
import com.kingfish.reactor.domain.model.jooq.tables.UserExt;
import com.kingfish.reactor.domain.model.jooq.tables.UserMessage;


/**
 * Convenience access to all tables in reactor_demo.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * 购物车表
     */
    public static final Cart CART = Cart.CART;

    /**
     * 用户优惠券表
     */
    public static final Coupon COUPON = Coupon.COUPON;

    /**
     * 会员信息表
     */
    public static final Member MEMBER = Member.MEMBER;

    /**
     * 订单主表
     */
    public static final Order ORDER = Order.ORDER;

    /**
     * 订单物流信息表
     */
    public static final OrderLogistics ORDER_LOGISTICS = OrderLogistics.ORDER_LOGISTICS;

    /**
     * 商品表
     */
    public static final Product PRODUCT = Product.PRODUCT;

    /**
     * 用户基础信息表
     */
    public static final User USER = User.USER;

    /**
     * 用户收货地址表
     */
    public static final UserAddress USER_ADDRESS = UserAddress.USER_ADDRESS;

    /**
     * 用户扩展信息表
     */
    public static final UserExt USER_EXT = UserExt.USER_EXT;

    /**
     * 用户消息表
     */
    public static final UserMessage USER_MESSAGE = UserMessage.USER_MESSAGE;
}
