/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.records;


import com.kingfish.reactor.domain.model.jooq.tables.Cart;
import com.kingfish.reactor.domain.model.jooq.tables.pojos.CartDO;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 购物车表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CartRecord extends UpdatableRecordImpl<CartRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reactor_demo.cart.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>reactor_demo.cart.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>reactor_demo.cart.user_id</code>. 用户ID
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>reactor_demo.cart.user_id</code>. 用户ID
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>reactor_demo.cart.product_id</code>. 商品ID
     */
    public void setProductId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>reactor_demo.cart.product_id</code>. 商品ID
     */
    public Long getProductId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>reactor_demo.cart.quantity</code>. 购买数量
     */
    public void setQuantity(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>reactor_demo.cart.quantity</code>. 购买数量
     */
    public Integer getQuantity() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>reactor_demo.cart.price</code>. 加入购物车时的单价
     */
    public void setPrice(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>reactor_demo.cart.price</code>. 加入购物车时的单价
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>reactor_demo.cart.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>reactor_demo.cart.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>reactor_demo.cart.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>reactor_demo.cart.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>reactor_demo.cart.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public void setDeleted(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>reactor_demo.cart.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public Byte getDeleted() {
        return (Byte) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CartRecord
     */
    public CartRecord() {
        super(Cart.CART);
    }

    /**
     * Create a detached, initialised CartRecord
     */
    public CartRecord(Long id, Long userId, Long productId, Integer quantity, BigDecimal price, LocalDateTime createTime, LocalDateTime updateTime, Byte deleted) {
        super(Cart.CART);

        setId(id);
        setUserId(userId);
        setProductId(productId);
        setQuantity(quantity);
        setPrice(price);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setDeleted(deleted);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CartRecord
     */
    public CartRecord(CartDO value) {
        super(Cart.CART);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setProductId(value.getProductId());
            setQuantity(value.getQuantity());
            setPrice(value.getPrice());
            setCreateTime(value.getCreateTime());
            setUpdateTime(value.getUpdateTime());
            setDeleted(value.getDeleted());
            resetChangedOnNotNull();
        }
    }
}
