/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.records;


import com.kingfish.reactor.domain.model.jooq.tables.Coupon;
import com.kingfish.reactor.domain.model.jooq.tables.pojos.CouponDO;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户优惠券表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CouponRecord extends UpdatableRecordImpl<CouponRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reactor_demo.coupon.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>reactor_demo.coupon.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>reactor_demo.coupon.user_id</code>. 用户ID
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>reactor_demo.coupon.user_id</code>. 用户ID
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>reactor_demo.coupon.threshold</code>. 使用门槛（满多少可用）
     */
    public void setThreshold(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>reactor_demo.coupon.threshold</code>. 使用门槛（满多少可用）
     */
    public BigDecimal getThreshold() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>reactor_demo.coupon.discount</code>. 优惠金额
     */
    public void setDiscount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>reactor_demo.coupon.discount</code>. 优惠金额
     */
    public BigDecimal getDiscount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>reactor_demo.coupon.status</code>. 状态 0-未使用 1-已使用 2-已过期
     */
    public void setStatus(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>reactor_demo.coupon.status</code>. 状态 0-未使用 1-已使用 2-已过期
     */
    public Byte getStatus() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>reactor_demo.coupon.expire_time</code>. 过期时间
     */
    public void setExpireTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>reactor_demo.coupon.expire_time</code>. 过期时间
     */
    public LocalDateTime getExpireTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>reactor_demo.coupon.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>reactor_demo.coupon.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>reactor_demo.coupon.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reactor_demo.coupon.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reactor_demo.coupon.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public void setDeleted(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>reactor_demo.coupon.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public Byte getDeleted() {
        return (Byte) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CouponRecord
     */
    public CouponRecord() {
        super(Coupon.COUPON);
    }

    /**
     * Create a detached, initialised CouponRecord
     */
    public CouponRecord(Long id, Long userId, BigDecimal threshold, BigDecimal discount, Byte status, LocalDateTime expireTime, LocalDateTime createTime, LocalDateTime updateTime, Byte deleted) {
        super(Coupon.COUPON);

        setId(id);
        setUserId(userId);
        setThreshold(threshold);
        setDiscount(discount);
        setStatus(status);
        setExpireTime(expireTime);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setDeleted(deleted);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CouponRecord
     */
    public CouponRecord(CouponDO value) {
        super(Coupon.COUPON);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setThreshold(value.getThreshold());
            setDiscount(value.getDiscount());
            setStatus(value.getStatus());
            setExpireTime(value.getExpireTime());
            setCreateTime(value.getCreateTime());
            setUpdateTime(value.getUpdateTime());
            setDeleted(value.getDeleted());
            resetChangedOnNotNull();
        }
    }
}
