/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.records;


import com.kingfish.reactor.domain.model.jooq.tables.Member;
import com.kingfish.reactor.domain.model.jooq.tables.pojos.MemberDO;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 会员信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MemberRecord extends UpdatableRecordImpl<MemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reactor_demo.member.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>reactor_demo.member.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>reactor_demo.member.user_id</code>. 用户ID
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>reactor_demo.member.user_id</code>. 用户ID
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>reactor_demo.member.level</code>. 会员等级
     */
    public void setLevel(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>reactor_demo.member.level</code>. 会员等级
     */
    public Integer getLevel() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>reactor_demo.member.discount</code>. 折扣率
     */
    public void setDiscount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>reactor_demo.member.discount</code>. 折扣率
     */
    public BigDecimal getDiscount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>reactor_demo.member.total_points</code>. 总积分
     */
    public void setTotalPoints(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>reactor_demo.member.total_points</code>. 总积分
     */
    public Long getTotalPoints() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>reactor_demo.member.expire_time</code>. 会员过期时间
     */
    public void setExpireTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>reactor_demo.member.expire_time</code>. 会员过期时间
     */
    public LocalDateTime getExpireTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>reactor_demo.member.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>reactor_demo.member.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>reactor_demo.member.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reactor_demo.member.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reactor_demo.member.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public void setDeleted(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>reactor_demo.member.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public Byte getDeleted() {
        return (Byte) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemberRecord
     */
    public MemberRecord() {
        super(Member.MEMBER);
    }

    /**
     * Create a detached, initialised MemberRecord
     */
    public MemberRecord(Long id, Long userId, Integer level, BigDecimal discount, Long totalPoints, LocalDateTime expireTime, LocalDateTime createTime, LocalDateTime updateTime, Byte deleted) {
        super(Member.MEMBER);

        setId(id);
        setUserId(userId);
        setLevel(level);
        setDiscount(discount);
        setTotalPoints(totalPoints);
        setExpireTime(expireTime);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setDeleted(deleted);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MemberRecord
     */
    public MemberRecord(MemberDO value) {
        super(Member.MEMBER);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setLevel(value.getLevel());
            setDiscount(value.getDiscount());
            setTotalPoints(value.getTotalPoints());
            setExpireTime(value.getExpireTime());
            setCreateTime(value.getCreateTime());
            setUpdateTime(value.getUpdateTime());
            setDeleted(value.getDeleted());
            resetChangedOnNotNull();
        }
    }
}
