/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.records;


import com.kingfish.reactor.domain.model.jooq.tables.OrderLogistics;
import com.kingfish.reactor.domain.model.jooq.tables.pojos.OrderLogisticsDO;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 订单物流信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderLogisticsRecord extends UpdatableRecordImpl<OrderLogisticsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reactor_demo.order_logistics.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>reactor_demo.order_logistics.logistics_id</code>. 物流ID
     */
    public void setLogisticsId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.logistics_id</code>. 物流ID
     */
    public Long getLogisticsId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>reactor_demo.order_logistics.order_id</code>. 订单ID
     */
    public void setOrderId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.order_id</code>. 订单ID
     */
    public Long getOrderId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>reactor_demo.order_logistics.company</code>. 物流公司
     */
    public void setCompany(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.company</code>. 物流公司
     */
    public String getCompany() {
        return (String) get(3);
    }

    /**
     * Setter for <code>reactor_demo.order_logistics.logistics_no</code>. 物流单号
     */
    public void setLogisticsNo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.logistics_no</code>. 物流单号
     */
    public String getLogisticsNo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>reactor_demo.order_logistics.status</code>. 物流状态
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.status</code>. 物流状态
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>reactor_demo.order_logistics.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>reactor_demo.order_logistics.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reactor_demo.order_logistics.deleted</code>. 删除标记 0-未删除
     * 1-已删除
     */
    public void setDeleted(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>reactor_demo.order_logistics.deleted</code>. 删除标记 0-未删除
     * 1-已删除
     */
    public Byte getDeleted() {
        return (Byte) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderLogisticsRecord
     */
    public OrderLogisticsRecord() {
        super(OrderLogistics.ORDER_LOGISTICS);
    }

    /**
     * Create a detached, initialised OrderLogisticsRecord
     */
    public OrderLogisticsRecord(Long id, Long logisticsId, Long orderId, String company, String logisticsNo, String status, LocalDateTime createTime, LocalDateTime updateTime, Byte deleted) {
        super(OrderLogistics.ORDER_LOGISTICS);

        setId(id);
        setLogisticsId(logisticsId);
        setOrderId(orderId);
        setCompany(company);
        setLogisticsNo(logisticsNo);
        setStatus(status);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setDeleted(deleted);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised OrderLogisticsRecord
     */
    public OrderLogisticsRecord(OrderLogisticsDO value) {
        super(OrderLogistics.ORDER_LOGISTICS);

        if (value != null) {
            setId(value.getId());
            setLogisticsId(value.getLogisticsId());
            setOrderId(value.getOrderId());
            setCompany(value.getCompany());
            setLogisticsNo(value.getLogisticsNo());
            setStatus(value.getStatus());
            setCreateTime(value.getCreateTime());
            setUpdateTime(value.getUpdateTime());
            setDeleted(value.getDeleted());
            resetChangedOnNotNull();
        }
    }
}
