/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.records;


import com.kingfish.reactor.domain.model.jooq.tables.Order;
import com.kingfish.reactor.domain.model.jooq.tables.pojos.OrderDO;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 订单主表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderRecord extends UpdatableRecordImpl<OrderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reactor_demo.order.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>reactor_demo.order.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>reactor_demo.order.order_id</code>. 订单ID
     */
    public void setOrderId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>reactor_demo.order.order_id</code>. 订单ID
     */
    public Long getOrderId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>reactor_demo.order.user_id</code>. 用户ID
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>reactor_demo.order.user_id</code>. 用户ID
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>reactor_demo.order.product_id</code>. 商品ID
     */
    public void setProductId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>reactor_demo.order.product_id</code>. 商品ID
     */
    public Long getProductId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>reactor_demo.order.quantity</code>. 商品数量
     */
    public void setQuantity(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>reactor_demo.order.quantity</code>. 商品数量
     */
    public Integer getQuantity() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>reactor_demo.order.order_no</code>. 订单编号
     */
    public void setOrderNo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>reactor_demo.order.order_no</code>. 订单编号
     */
    public String getOrderNo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>reactor_demo.order.total_amount</code>. 订单总金额
     */
    public void setTotalAmount(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>reactor_demo.order.total_amount</code>. 订单总金额
     */
    public BigDecimal getTotalAmount() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>reactor_demo.order.pay_status</code>. 支付状态 0-未支付 1-已支付
     */
    public void setPayStatus(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>reactor_demo.order.pay_status</code>. 支付状态 0-未支付 1-已支付
     */
    public Byte getPayStatus() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>reactor_demo.order.order_status</code>. 订单状态 0-待付款 1-待发货
     * 2-待收货 3-已完成 4-已取消
     */
    public void setOrderStatus(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>reactor_demo.order.order_status</code>. 订单状态 0-待付款 1-待发货
     * 2-待收货 3-已完成 4-已取消
     */
    public Byte getOrderStatus() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>reactor_demo.order.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>reactor_demo.order.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>reactor_demo.order.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>reactor_demo.order.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>reactor_demo.order.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public void setDeleted(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>reactor_demo.order.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public Byte getDeleted() {
        return (Byte) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderRecord
     */
    public OrderRecord() {
        super(Order.ORDER);
    }

    /**
     * Create a detached, initialised OrderRecord
     */
    public OrderRecord(Long id, Long orderId, Long userId, Long productId, Integer quantity, String orderNo, BigDecimal totalAmount, Byte payStatus, Byte orderStatus, LocalDateTime createTime, LocalDateTime updateTime, Byte deleted) {
        super(Order.ORDER);

        setId(id);
        setOrderId(orderId);
        setUserId(userId);
        setProductId(productId);
        setQuantity(quantity);
        setOrderNo(orderNo);
        setTotalAmount(totalAmount);
        setPayStatus(payStatus);
        setOrderStatus(orderStatus);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setDeleted(deleted);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised OrderRecord
     */
    public OrderRecord(OrderDO value) {
        super(Order.ORDER);

        if (value != null) {
            setId(value.getId());
            setOrderId(value.getOrderId());
            setUserId(value.getUserId());
            setProductId(value.getProductId());
            setQuantity(value.getQuantity());
            setOrderNo(value.getOrderNo());
            setTotalAmount(value.getTotalAmount());
            setPayStatus(value.getPayStatus());
            setOrderStatus(value.getOrderStatus());
            setCreateTime(value.getCreateTime());
            setUpdateTime(value.getUpdateTime());
            setDeleted(value.getDeleted());
            resetChangedOnNotNull();
        }
    }
}
