/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.records;


import com.kingfish.reactor.domain.model.jooq.tables.Product;
import com.kingfish.reactor.domain.model.jooq.tables.pojos.ProductDO;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 商品表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reactor_demo.product.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>reactor_demo.product.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>reactor_demo.product.product_id</code>. 商品ID
     */
    public void setProductId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>reactor_demo.product.product_id</code>. 商品ID
     */
    public Long getProductId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>reactor_demo.product.product_name</code>. 商品名称
     */
    public void setProductName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reactor_demo.product.product_name</code>. 商品名称
     */
    public String getProductName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reactor_demo.product.price</code>. 销售价格
     */
    public void setPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>reactor_demo.product.price</code>. 销售价格
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>reactor_demo.product.stock</code>. 库存数量
     */
    public void setStock(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>reactor_demo.product.stock</code>. 库存数量
     */
    public Integer getStock() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>reactor_demo.product.status</code>. 商品状态 0-下架 1-上架
     */
    public void setStatus(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>reactor_demo.product.status</code>. 商品状态 0-下架 1-上架
     */
    public Byte getStatus() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>reactor_demo.product.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>reactor_demo.product.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>reactor_demo.product.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reactor_demo.product.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reactor_demo.product.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public void setDeleted(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>reactor_demo.product.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public Byte getDeleted() {
        return (Byte) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(Long id, Long productId, String productName, BigDecimal price, Integer stock, Byte status, LocalDateTime createTime, LocalDateTime updateTime, Byte deleted) {
        super(Product.PRODUCT);

        setId(id);
        setProductId(productId);
        setProductName(productName);
        setPrice(price);
        setStock(stock);
        setStatus(status);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setDeleted(deleted);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(ProductDO value) {
        super(Product.PRODUCT);

        if (value != null) {
            setId(value.getId());
            setProductId(value.getProductId());
            setProductName(value.getProductName());
            setPrice(value.getPrice());
            setStock(value.getStock());
            setStatus(value.getStatus());
            setCreateTime(value.getCreateTime());
            setUpdateTime(value.getUpdateTime());
            setDeleted(value.getDeleted());
            resetChangedOnNotNull();
        }
    }
}
