/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.records;


import com.kingfish.reactor.domain.model.jooq.tables.UserAddress;
import com.kingfish.reactor.domain.model.jooq.tables.pojos.UserAddressDO;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户收货地址表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserAddressRecord extends UpdatableRecordImpl<UserAddressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reactor_demo.user_address.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>reactor_demo.user_address.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>reactor_demo.user_address.address_id</code>. 地址ID
     */
    public void setAddressId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>reactor_demo.user_address.address_id</code>. 地址ID
     */
    public Long getAddressId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>reactor_demo.user_address.user_id</code>. 用户ID
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>reactor_demo.user_address.user_id</code>. 用户ID
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>reactor_demo.user_address.receiver</code>. 收件人姓名
     */
    public void setReceiver(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>reactor_demo.user_address.receiver</code>. 收件人姓名
     */
    public String getReceiver() {
        return (String) get(3);
    }

    /**
     * Setter for <code>reactor_demo.user_address.phone</code>. 收件人电话
     */
    public void setPhone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>reactor_demo.user_address.phone</code>. 收件人电话
     */
    public String getPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>reactor_demo.user_address.province</code>. 省份
     */
    public void setProvince(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>reactor_demo.user_address.province</code>. 省份
     */
    public String getProvince() {
        return (String) get(5);
    }

    /**
     * Setter for <code>reactor_demo.user_address.city</code>. 城市
     */
    public void setCity(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>reactor_demo.user_address.city</code>. 城市
     */
    public String getCity() {
        return (String) get(6);
    }

    /**
     * Setter for <code>reactor_demo.user_address.detail</code>. 详细地址
     */
    public void setDetail(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>reactor_demo.user_address.detail</code>. 详细地址
     */
    public String getDetail() {
        return (String) get(7);
    }

    /**
     * Setter for <code>reactor_demo.user_address.is_default</code>. 是否默认地址 0-否
     * 1-是
     */
    public void setIsDefault(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>reactor_demo.user_address.is_default</code>. 是否默认地址 0-否
     * 1-是
     */
    public Byte getIsDefault() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>reactor_demo.user_address.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>reactor_demo.user_address.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>reactor_demo.user_address.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>reactor_demo.user_address.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>reactor_demo.user_address.deleted</code>. 删除标记 0-未删除
     * 1-已删除
     */
    public void setDeleted(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>reactor_demo.user_address.deleted</code>. 删除标记 0-未删除
     * 1-已删除
     */
    public Byte getDeleted() {
        return (Byte) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAddressRecord
     */
    public UserAddressRecord() {
        super(UserAddress.USER_ADDRESS);
    }

    /**
     * Create a detached, initialised UserAddressRecord
     */
    public UserAddressRecord(Long id, Long addressId, Long userId, String receiver, String phone, String province, String city, String detail, Byte isDefault, LocalDateTime createTime, LocalDateTime updateTime, Byte deleted) {
        super(UserAddress.USER_ADDRESS);

        setId(id);
        setAddressId(addressId);
        setUserId(userId);
        setReceiver(receiver);
        setPhone(phone);
        setProvince(province);
        setCity(city);
        setDetail(detail);
        setIsDefault(isDefault);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setDeleted(deleted);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserAddressRecord
     */
    public UserAddressRecord(UserAddressDO value) {
        super(UserAddress.USER_ADDRESS);

        if (value != null) {
            setId(value.getId());
            setAddressId(value.getAddressId());
            setUserId(value.getUserId());
            setReceiver(value.getReceiver());
            setPhone(value.getPhone());
            setProvince(value.getProvince());
            setCity(value.getCity());
            setDetail(value.getDetail());
            setIsDefault(value.getIsDefault());
            setCreateTime(value.getCreateTime());
            setUpdateTime(value.getUpdateTime());
            setDeleted(value.getDeleted());
            resetChangedOnNotNull();
        }
    }
}
