/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.records;


import com.kingfish.reactor.domain.model.jooq.tables.User;
import com.kingfish.reactor.domain.model.jooq.tables.pojos.UserDO;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户基础信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reactor_demo.user.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>reactor_demo.user.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>reactor_demo.user.username</code>. 登录账号
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>reactor_demo.user.username</code>. 登录账号
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>reactor_demo.user.password</code>. 加密后密码
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reactor_demo.user.password</code>. 加密后密码
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reactor_demo.user.status</code>. 用户状态 0-禁用 1-正常
     */
    public void setStatus(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>reactor_demo.user.status</code>. 用户状态 0-禁用 1-正常
     */
    public Byte getStatus() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>reactor_demo.user.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>reactor_demo.user.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>reactor_demo.user.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>reactor_demo.user.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>reactor_demo.user.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public void setDeleted(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>reactor_demo.user.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public Byte getDeleted() {
        return (Byte) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long id, String username, String password, Byte status, LocalDateTime createTime, LocalDateTime updateTime, Byte deleted) {
        super(User.USER);

        setId(id);
        setUsername(username);
        setPassword(password);
        setStatus(status);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setDeleted(deleted);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(UserDO value) {
        super(User.USER);

        if (value != null) {
            setId(value.getId());
            setUsername(value.getUsername());
            setPassword(value.getPassword());
            setStatus(value.getStatus());
            setCreateTime(value.getCreateTime());
            setUpdateTime(value.getUpdateTime());
            setDeleted(value.getDeleted());
            resetChangedOnNotNull();
        }
    }
}
