/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.records;


import com.kingfish.reactor.domain.model.jooq.tables.UserMessage;
import com.kingfish.reactor.domain.model.jooq.tables.pojos.UserMessageDO;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户消息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserMessageRecord extends UpdatableRecordImpl<UserMessageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reactor_demo.user_message.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>reactor_demo.user_message.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>reactor_demo.user_message.msg_id</code>. 消息ID
     */
    public void setMsgId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>reactor_demo.user_message.msg_id</code>. 消息ID
     */
    public Long getMsgId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>reactor_demo.user_message.user_id</code>. 用户ID
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>reactor_demo.user_message.user_id</code>. 用户ID
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>reactor_demo.user_message.title</code>. 消息标题
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>reactor_demo.user_message.title</code>. 消息标题
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>reactor_demo.user_message.content</code>. 消息内容
     */
    public void setContent(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>reactor_demo.user_message.content</code>. 消息内容
     */
    public String getContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>reactor_demo.user_message.is_read</code>. 是否已读 0-未读 1-已读
     */
    public void setIsRead(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>reactor_demo.user_message.is_read</code>. 是否已读 0-未读 1-已读
     */
    public Byte getIsRead() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>reactor_demo.user_message.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>reactor_demo.user_message.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>reactor_demo.user_message.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reactor_demo.user_message.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reactor_demo.user_message.deleted</code>. 删除标记 0-未删除
     * 1-已删除
     */
    public void setDeleted(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>reactor_demo.user_message.deleted</code>. 删除标记 0-未删除
     * 1-已删除
     */
    public Byte getDeleted() {
        return (Byte) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserMessageRecord
     */
    public UserMessageRecord() {
        super(UserMessage.USER_MESSAGE);
    }

    /**
     * Create a detached, initialised UserMessageRecord
     */
    public UserMessageRecord(Long id, Long msgId, Long userId, String title, String content, Byte isRead, LocalDateTime createTime, LocalDateTime updateTime, Byte deleted) {
        super(UserMessage.USER_MESSAGE);

        setId(id);
        setMsgId(msgId);
        setUserId(userId);
        setTitle(title);
        setContent(content);
        setIsRead(isRead);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setDeleted(deleted);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserMessageRecord
     */
    public UserMessageRecord(UserMessageDO value) {
        super(UserMessage.USER_MESSAGE);

        if (value != null) {
            setId(value.getId());
            setMsgId(value.getMsgId());
            setUserId(value.getUserId());
            setTitle(value.getTitle());
            setContent(value.getContent());
            setIsRead(value.getIsRead());
            setCreateTime(value.getCreateTime());
            setUpdateTime(value.getUpdateTime());
            setDeleted(value.getDeleted());
            resetChangedOnNotNull();
        }
    }
}
