/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables.records;


import com.kingfish.reactor.domain.model.jooq.tables.UserExt;
import com.kingfish.reactor.domain.model.jooq.tables.pojos.UserExtDO;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户扩展信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserExtRecord extends UpdatableRecordImpl<UserExtRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>reactor_demo.user_ext.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>reactor_demo.user_ext.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>reactor_demo.user_ext.user_id</code>. 用户ID
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>reactor_demo.user_ext.user_id</code>. 用户ID
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>reactor_demo.user_ext.real_name</code>. 真实姓名
     */
    public void setRealName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reactor_demo.user_ext.real_name</code>. 真实姓名
     */
    public String getRealName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reactor_demo.user_ext.id_card</code>. 身份证号
     */
    public void setIdCard(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>reactor_demo.user_ext.id_card</code>. 身份证号
     */
    public String getIdCard() {
        return (String) get(3);
    }

    /**
     * Setter for <code>reactor_demo.user_ext.phone</code>. 手机号
     */
    public void setPhone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>reactor_demo.user_ext.phone</code>. 手机号
     */
    public String getPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>reactor_demo.user_ext.email</code>. 邮箱
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>reactor_demo.user_ext.email</code>. 邮箱
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>reactor_demo.user_ext.sex</code>. 性别 0-未知 1-男 2-女
     */
    public void setSex(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>reactor_demo.user_ext.sex</code>. 性别 0-未知 1-男 2-女
     */
    public Byte getSex() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>reactor_demo.user_ext.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>reactor_demo.user_ext.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>reactor_demo.user_ext.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>reactor_demo.user_ext.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>reactor_demo.user_ext.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public void setDeleted(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>reactor_demo.user_ext.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public Byte getDeleted() {
        return (Byte) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserExtRecord
     */
    public UserExtRecord() {
        super(UserExt.USER_EXT);
    }

    /**
     * Create a detached, initialised UserExtRecord
     */
    public UserExtRecord(Long id, Long userId, String realName, String idCard, String phone, String email, Byte sex, LocalDateTime createTime, LocalDateTime updateTime, Byte deleted) {
        super(UserExt.USER_EXT);

        setId(id);
        setUserId(userId);
        setRealName(realName);
        setIdCard(idCard);
        setPhone(phone);
        setEmail(email);
        setSex(sex);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setDeleted(deleted);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserExtRecord
     */
    public UserExtRecord(UserExtDO value) {
        super(UserExt.USER_EXT);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setRealName(value.getRealName());
            setIdCard(value.getIdCard());
            setPhone(value.getPhone());
            setEmail(value.getEmail());
            setSex(value.getSex());
            setCreateTime(value.getCreateTime());
            setUpdateTime(value.getUpdateTime());
            setDeleted(value.getDeleted());
            resetChangedOnNotNull();
        }
    }
}
