/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables;


import com.kingfish.reactor.domain.model.jooq.Indexes;
import com.kingfish.reactor.domain.model.jooq.Keys;
import com.kingfish.reactor.domain.model.jooq.ReactorDemo;
import com.kingfish.reactor.domain.model.jooq.tables.records.CartRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 购物车表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Cart extends TableImpl<CartRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reactor_demo.cart</code>
     */
    public static final Cart CART = new Cart();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CartRecord> getRecordType() {
        return CartRecord.class;
    }

    /**
     * The column <code>reactor_demo.cart.id</code>. 主键ID
     */
    public final TableField<CartRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>reactor_demo.cart.user_id</code>. 用户ID
     */
    public final TableField<CartRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "用户ID");

    /**
     * The column <code>reactor_demo.cart.product_id</code>. 商品ID
     */
    public final TableField<CartRecord, Long> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.BIGINT.nullable(false), this, "商品ID");

    /**
     * The column <code>reactor_demo.cart.quantity</code>. 购买数量
     */
    public final TableField<CartRecord, Integer> QUANTITY = createField(DSL.name("quantity"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "购买数量");

    /**
     * The column <code>reactor_demo.cart.price</code>. 加入购物车时的单价
     */
    public final TableField<CartRecord, BigDecimal> PRICE = createField(DSL.name("price"), SQLDataType.DECIMAL(10, 2).nullable(false), this, "加入购物车时的单价");

    /**
     * The column <code>reactor_demo.cart.create_time</code>. 创建时间
     */
    public final TableField<CartRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>reactor_demo.cart.update_time</code>. 更新时间
     */
    public final TableField<CartRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "更新时间");

    /**
     * The column <code>reactor_demo.cart.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public final TableField<CartRecord, Byte> DELETED = createField(DSL.name("deleted"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "删除标记 0-未删除 1-已删除");

    private Cart(Name alias, Table<CartRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Cart(Name alias, Table<CartRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("购物车表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reactor_demo.cart</code> table reference
     */
    public Cart(String alias) {
        this(DSL.name(alias), CART);
    }

    /**
     * Create an aliased <code>reactor_demo.cart</code> table reference
     */
    public Cart(Name alias) {
        this(alias, CART);
    }

    /**
     * Create a <code>reactor_demo.cart</code> table reference
     */
    public Cart() {
        this(DSL.name("cart"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ReactorDemo.REACTOR_DEMO;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CART_IDX_USER_ID);
    }

    @Override
    public Identity<CartRecord, Long> getIdentity() {
        return (Identity<CartRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CartRecord> getPrimaryKey() {
        return Keys.KEY_CART_PRIMARY;
    }

    @Override
    public Cart as(String alias) {
        return new Cart(DSL.name(alias), this);
    }

    @Override
    public Cart as(Name alias) {
        return new Cart(alias, this);
    }

    @Override
    public Cart as(Table<?> alias) {
        return new Cart(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cart rename(String name) {
        return new Cart(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cart rename(Name name) {
        return new Cart(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cart rename(Table<?> name) {
        return new Cart(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cart where(Condition condition) {
        return new Cart(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cart where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cart where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cart where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cart where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cart where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cart where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cart where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cart whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cart whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
