/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables;


import com.kingfish.reactor.domain.model.jooq.Indexes;
import com.kingfish.reactor.domain.model.jooq.Keys;
import com.kingfish.reactor.domain.model.jooq.ReactorDemo;
import com.kingfish.reactor.domain.model.jooq.tables.records.CouponRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 用户优惠券表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Coupon extends TableImpl<CouponRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reactor_demo.coupon</code>
     */
    public static final Coupon COUPON = new Coupon();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CouponRecord> getRecordType() {
        return CouponRecord.class;
    }

    /**
     * The column <code>reactor_demo.coupon.id</code>. 主键ID
     */
    public final TableField<CouponRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>reactor_demo.coupon.user_id</code>. 用户ID
     */
    public final TableField<CouponRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "用户ID");

    /**
     * The column <code>reactor_demo.coupon.threshold</code>. 使用门槛（满多少可用）
     */
    public final TableField<CouponRecord, BigDecimal> THRESHOLD = createField(DSL.name("threshold"), SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this, "使用门槛（满多少可用）");

    /**
     * The column <code>reactor_demo.coupon.discount</code>. 优惠金额
     */
    public final TableField<CouponRecord, BigDecimal> DISCOUNT = createField(DSL.name("discount"), SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this, "优惠金额");

    /**
     * The column <code>reactor_demo.coupon.status</code>. 状态 0-未使用 1-已使用 2-已过期
     */
    public final TableField<CouponRecord, Byte> STATUS = createField(DSL.name("status"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "状态 0-未使用 1-已使用 2-已过期");

    /**
     * The column <code>reactor_demo.coupon.expire_time</code>. 过期时间
     */
    public final TableField<CouponRecord, LocalDateTime> EXPIRE_TIME = createField(DSL.name("expire_time"), SQLDataType.LOCALDATETIME(0), this, "过期时间");

    /**
     * The column <code>reactor_demo.coupon.create_time</code>. 创建时间
     */
    public final TableField<CouponRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>reactor_demo.coupon.update_time</code>. 更新时间
     */
    public final TableField<CouponRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "更新时间");

    /**
     * The column <code>reactor_demo.coupon.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public final TableField<CouponRecord, Byte> DELETED = createField(DSL.name("deleted"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "删除标记 0-未删除 1-已删除");

    private Coupon(Name alias, Table<CouponRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Coupon(Name alias, Table<CouponRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("用户优惠券表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reactor_demo.coupon</code> table reference
     */
    public Coupon(String alias) {
        this(DSL.name(alias), COUPON);
    }

    /**
     * Create an aliased <code>reactor_demo.coupon</code> table reference
     */
    public Coupon(Name alias) {
        this(alias, COUPON);
    }

    /**
     * Create a <code>reactor_demo.coupon</code> table reference
     */
    public Coupon() {
        this(DSL.name("coupon"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ReactorDemo.REACTOR_DEMO;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.COUPON_IDX_USER_ID);
    }

    @Override
    public Identity<CouponRecord, Long> getIdentity() {
        return (Identity<CouponRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CouponRecord> getPrimaryKey() {
        return Keys.KEY_COUPON_PRIMARY;
    }

    @Override
    public Coupon as(String alias) {
        return new Coupon(DSL.name(alias), this);
    }

    @Override
    public Coupon as(Name alias) {
        return new Coupon(alias, this);
    }

    @Override
    public Coupon as(Table<?> alias) {
        return new Coupon(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Coupon rename(String name) {
        return new Coupon(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Coupon rename(Name name) {
        return new Coupon(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Coupon rename(Table<?> name) {
        return new Coupon(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Coupon where(Condition condition) {
        return new Coupon(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Coupon where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Coupon where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Coupon where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Coupon where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Coupon where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Coupon where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Coupon where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Coupon whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Coupon whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
