/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables;


import com.kingfish.reactor.domain.model.jooq.Indexes;
import com.kingfish.reactor.domain.model.jooq.Keys;
import com.kingfish.reactor.domain.model.jooq.ReactorDemo;
import com.kingfish.reactor.domain.model.jooq.tables.records.OrderLogisticsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 订单物流信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderLogistics extends TableImpl<OrderLogisticsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reactor_demo.order_logistics</code>
     */
    public static final OrderLogistics ORDER_LOGISTICS = new OrderLogistics();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderLogisticsRecord> getRecordType() {
        return OrderLogisticsRecord.class;
    }

    /**
     * The column <code>reactor_demo.order_logistics.id</code>. 主键ID
     */
    public final TableField<OrderLogisticsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>reactor_demo.order_logistics.logistics_id</code>. 物流ID
     */
    public final TableField<OrderLogisticsRecord, Long> LOGISTICS_ID = createField(DSL.name("logistics_id"), SQLDataType.BIGINT.nullable(false), this, "物流ID");

    /**
     * The column <code>reactor_demo.order_logistics.order_id</code>. 订单ID
     */
    public final TableField<OrderLogisticsRecord, Long> ORDER_ID = createField(DSL.name("order_id"), SQLDataType.BIGINT.nullable(false), this, "订单ID");

    /**
     * The column <code>reactor_demo.order_logistics.company</code>. 物流公司
     */
    public final TableField<OrderLogisticsRecord, String> COMPANY = createField(DSL.name("company"), SQLDataType.VARCHAR(64), this, "物流公司");

    /**
     * The column <code>reactor_demo.order_logistics.logistics_no</code>. 物流单号
     */
    public final TableField<OrderLogisticsRecord, String> LOGISTICS_NO = createField(DSL.name("logistics_no"), SQLDataType.VARCHAR(64), this, "物流单号");

    /**
     * The column <code>reactor_demo.order_logistics.status</code>. 物流状态
     */
    public final TableField<OrderLogisticsRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(32), this, "物流状态");

    /**
     * The column <code>reactor_demo.order_logistics.create_time</code>. 创建时间
     */
    public final TableField<OrderLogisticsRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>reactor_demo.order_logistics.update_time</code>. 更新时间
     */
    public final TableField<OrderLogisticsRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "更新时间");

    /**
     * The column <code>reactor_demo.order_logistics.deleted</code>. 删除标记 0-未删除
     * 1-已删除
     */
    public final TableField<OrderLogisticsRecord, Byte> DELETED = createField(DSL.name("deleted"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "删除标记 0-未删除 1-已删除");

    private OrderLogistics(Name alias, Table<OrderLogisticsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OrderLogistics(Name alias, Table<OrderLogisticsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("订单物流信息表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reactor_demo.order_logistics</code> table
     * reference
     */
    public OrderLogistics(String alias) {
        this(DSL.name(alias), ORDER_LOGISTICS);
    }

    /**
     * Create an aliased <code>reactor_demo.order_logistics</code> table
     * reference
     */
    public OrderLogistics(Name alias) {
        this(alias, ORDER_LOGISTICS);
    }

    /**
     * Create a <code>reactor_demo.order_logistics</code> table reference
     */
    public OrderLogistics() {
        this(DSL.name("order_logistics"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ReactorDemo.REACTOR_DEMO;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ORDER_LOGISTICS_IDX_ORDER_ID);
    }

    @Override
    public Identity<OrderLogisticsRecord, Long> getIdentity() {
        return (Identity<OrderLogisticsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrderLogisticsRecord> getPrimaryKey() {
        return Keys.KEY_ORDER_LOGISTICS_PRIMARY;
    }

    @Override
    public OrderLogistics as(String alias) {
        return new OrderLogistics(DSL.name(alias), this);
    }

    @Override
    public OrderLogistics as(Name alias) {
        return new OrderLogistics(alias, this);
    }

    @Override
    public OrderLogistics as(Table<?> alias) {
        return new OrderLogistics(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderLogistics rename(String name) {
        return new OrderLogistics(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderLogistics rename(Name name) {
        return new OrderLogistics(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderLogistics rename(Table<?> name) {
        return new OrderLogistics(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderLogistics where(Condition condition) {
        return new OrderLogistics(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderLogistics where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderLogistics where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderLogistics where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderLogistics where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderLogistics where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderLogistics where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderLogistics where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderLogistics whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderLogistics whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
