/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables;


import com.kingfish.reactor.domain.model.jooq.Indexes;
import com.kingfish.reactor.domain.model.jooq.Keys;
import com.kingfish.reactor.domain.model.jooq.ReactorDemo;
import com.kingfish.reactor.domain.model.jooq.tables.records.UserMessageRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 用户消息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserMessage extends TableImpl<UserMessageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reactor_demo.user_message</code>
     */
    public static final UserMessage USER_MESSAGE = new UserMessage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserMessageRecord> getRecordType() {
        return UserMessageRecord.class;
    }

    /**
     * The column <code>reactor_demo.user_message.id</code>. 主键ID
     */
    public final TableField<UserMessageRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>reactor_demo.user_message.msg_id</code>. 消息ID
     */
    public final TableField<UserMessageRecord, Long> MSG_ID = createField(DSL.name("msg_id"), SQLDataType.BIGINT.nullable(false), this, "消息ID");

    /**
     * The column <code>reactor_demo.user_message.user_id</code>. 用户ID
     */
    public final TableField<UserMessageRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "用户ID");

    /**
     * The column <code>reactor_demo.user_message.title</code>. 消息标题
     */
    public final TableField<UserMessageRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(128).nullable(false), this, "消息标题");

    /**
     * The column <code>reactor_demo.user_message.content</code>. 消息内容
     */
    public final TableField<UserMessageRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB, this, "消息内容");

    /**
     * The column <code>reactor_demo.user_message.is_read</code>. 是否已读 0-未读 1-已读
     */
    public final TableField<UserMessageRecord, Byte> IS_READ = createField(DSL.name("is_read"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "是否已读 0-未读 1-已读");

    /**
     * The column <code>reactor_demo.user_message.create_time</code>. 创建时间
     */
    public final TableField<UserMessageRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>reactor_demo.user_message.update_time</code>. 更新时间
     */
    public final TableField<UserMessageRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "更新时间");

    /**
     * The column <code>reactor_demo.user_message.deleted</code>. 删除标记 0-未删除
     * 1-已删除
     */
    public final TableField<UserMessageRecord, Byte> DELETED = createField(DSL.name("deleted"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "删除标记 0-未删除 1-已删除");

    private UserMessage(Name alias, Table<UserMessageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserMessage(Name alias, Table<UserMessageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("用户消息表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reactor_demo.user_message</code> table reference
     */
    public UserMessage(String alias) {
        this(DSL.name(alias), USER_MESSAGE);
    }

    /**
     * Create an aliased <code>reactor_demo.user_message</code> table reference
     */
    public UserMessage(Name alias) {
        this(alias, USER_MESSAGE);
    }

    /**
     * Create a <code>reactor_demo.user_message</code> table reference
     */
    public UserMessage() {
        this(DSL.name("user_message"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ReactorDemo.REACTOR_DEMO;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.USER_MESSAGE_IDX_USER_ID);
    }

    @Override
    public Identity<UserMessageRecord, Long> getIdentity() {
        return (Identity<UserMessageRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserMessageRecord> getPrimaryKey() {
        return Keys.KEY_USER_MESSAGE_PRIMARY;
    }

    @Override
    public UserMessage as(String alias) {
        return new UserMessage(DSL.name(alias), this);
    }

    @Override
    public UserMessage as(Name alias) {
        return new UserMessage(alias, this);
    }

    @Override
    public UserMessage as(Table<?> alias) {
        return new UserMessage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMessage rename(String name) {
        return new UserMessage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMessage rename(Name name) {
        return new UserMessage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMessage rename(Table<?> name) {
        return new UserMessage(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMessage where(Condition condition) {
        return new UserMessage(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMessage where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMessage where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMessage where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserMessage where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserMessage where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserMessage where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserMessage where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMessage whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMessage whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
