/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables;


import com.kingfish.reactor.domain.model.jooq.Indexes;
import com.kingfish.reactor.domain.model.jooq.Keys;
import com.kingfish.reactor.domain.model.jooq.ReactorDemo;
import com.kingfish.reactor.domain.model.jooq.tables.records.UserAddressRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 用户收货地址表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserAddress extends TableImpl<UserAddressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reactor_demo.user_address</code>
     */
    public static final UserAddress USER_ADDRESS = new UserAddress();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserAddressRecord> getRecordType() {
        return UserAddressRecord.class;
    }

    /**
     * The column <code>reactor_demo.user_address.id</code>. 主键ID
     */
    public final TableField<UserAddressRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>reactor_demo.user_address.address_id</code>. 地址ID
     */
    public final TableField<UserAddressRecord, Long> ADDRESS_ID = createField(DSL.name("address_id"), SQLDataType.BIGINT.nullable(false), this, "地址ID");

    /**
     * The column <code>reactor_demo.user_address.user_id</code>. 用户ID
     */
    public final TableField<UserAddressRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "用户ID");

    /**
     * The column <code>reactor_demo.user_address.receiver</code>. 收件人姓名
     */
    public final TableField<UserAddressRecord, String> RECEIVER = createField(DSL.name("receiver"), SQLDataType.VARCHAR(32).nullable(false), this, "收件人姓名");

    /**
     * The column <code>reactor_demo.user_address.phone</code>. 收件人电话
     */
    public final TableField<UserAddressRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(20).nullable(false), this, "收件人电话");

    /**
     * The column <code>reactor_demo.user_address.province</code>. 省份
     */
    public final TableField<UserAddressRecord, String> PROVINCE = createField(DSL.name("province"), SQLDataType.VARCHAR(32), this, "省份");

    /**
     * The column <code>reactor_demo.user_address.city</code>. 城市
     */
    public final TableField<UserAddressRecord, String> CITY = createField(DSL.name("city"), SQLDataType.VARCHAR(32), this, "城市");

    /**
     * The column <code>reactor_demo.user_address.detail</code>. 详细地址
     */
    public final TableField<UserAddressRecord, String> DETAIL = createField(DSL.name("detail"), SQLDataType.VARCHAR(256), this, "详细地址");

    /**
     * The column <code>reactor_demo.user_address.is_default</code>. 是否默认地址 0-否
     * 1-是
     */
    public final TableField<UserAddressRecord, Byte> IS_DEFAULT = createField(DSL.name("is_default"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "是否默认地址 0-否 1-是");

    /**
     * The column <code>reactor_demo.user_address.create_time</code>. 创建时间
     */
    public final TableField<UserAddressRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>reactor_demo.user_address.update_time</code>. 更新时间
     */
    public final TableField<UserAddressRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "更新时间");

    /**
     * The column <code>reactor_demo.user_address.deleted</code>. 删除标记 0-未删除
     * 1-已删除
     */
    public final TableField<UserAddressRecord, Byte> DELETED = createField(DSL.name("deleted"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "删除标记 0-未删除 1-已删除");

    private UserAddress(Name alias, Table<UserAddressRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserAddress(Name alias, Table<UserAddressRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("用户收货地址表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reactor_demo.user_address</code> table reference
     */
    public UserAddress(String alias) {
        this(DSL.name(alias), USER_ADDRESS);
    }

    /**
     * Create an aliased <code>reactor_demo.user_address</code> table reference
     */
    public UserAddress(Name alias) {
        this(alias, USER_ADDRESS);
    }

    /**
     * Create a <code>reactor_demo.user_address</code> table reference
     */
    public UserAddress() {
        this(DSL.name("user_address"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ReactorDemo.REACTOR_DEMO;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.USER_ADDRESS_IDX_USER_ID);
    }

    @Override
    public Identity<UserAddressRecord, Long> getIdentity() {
        return (Identity<UserAddressRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserAddressRecord> getPrimaryKey() {
        return Keys.KEY_USER_ADDRESS_PRIMARY;
    }

    @Override
    public UserAddress as(String alias) {
        return new UserAddress(DSL.name(alias), this);
    }

    @Override
    public UserAddress as(Name alias) {
        return new UserAddress(alias, this);
    }

    @Override
    public UserAddress as(Table<?> alias) {
        return new UserAddress(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAddress rename(String name) {
        return new UserAddress(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAddress rename(Name name) {
        return new UserAddress(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAddress rename(Table<?> name) {
        return new UserAddress(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAddress where(Condition condition) {
        return new UserAddress(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAddress where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAddress where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAddress where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAddress where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAddress where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAddress where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAddress where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAddress whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAddress whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
