/*
 * This file is generated by jOOQ.
 */
package com.kingfish.reactor.domain.model.jooq.tables;


import com.kingfish.reactor.domain.model.jooq.Keys;
import com.kingfish.reactor.domain.model.jooq.ReactorDemo;
import com.kingfish.reactor.domain.model.jooq.tables.records.UserExtRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 用户扩展信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserExt extends TableImpl<UserExtRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reactor_demo.user_ext</code>
     */
    public static final UserExt USER_EXT = new UserExt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserExtRecord> getRecordType() {
        return UserExtRecord.class;
    }

    /**
     * The column <code>reactor_demo.user_ext.id</code>. 主键ID
     */
    public final TableField<UserExtRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>reactor_demo.user_ext.user_id</code>. 用户ID
     */
    public final TableField<UserExtRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "用户ID");

    /**
     * The column <code>reactor_demo.user_ext.real_name</code>. 真实姓名
     */
    public final TableField<UserExtRecord, String> REAL_NAME = createField(DSL.name("real_name"), SQLDataType.VARCHAR(32), this, "真实姓名");

    /**
     * The column <code>reactor_demo.user_ext.id_card</code>. 身份证号
     */
    public final TableField<UserExtRecord, String> ID_CARD = createField(DSL.name("id_card"), SQLDataType.VARCHAR(32), this, "身份证号");

    /**
     * The column <code>reactor_demo.user_ext.phone</code>. 手机号
     */
    public final TableField<UserExtRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(20), this, "手机号");

    /**
     * The column <code>reactor_demo.user_ext.email</code>. 邮箱
     */
    public final TableField<UserExtRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(64), this, "邮箱");

    /**
     * The column <code>reactor_demo.user_ext.sex</code>. 性别 0-未知 1-男 2-女
     */
    public final TableField<UserExtRecord, Byte> SEX = createField(DSL.name("sex"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "性别 0-未知 1-男 2-女");

    /**
     * The column <code>reactor_demo.user_ext.create_time</code>. 创建时间
     */
    public final TableField<UserExtRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>reactor_demo.user_ext.update_time</code>. 更新时间
     */
    public final TableField<UserExtRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "更新时间");

    /**
     * The column <code>reactor_demo.user_ext.deleted</code>. 删除标记 0-未删除 1-已删除
     */
    public final TableField<UserExtRecord, Byte> DELETED = createField(DSL.name("deleted"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "删除标记 0-未删除 1-已删除");

    private UserExt(Name alias, Table<UserExtRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserExt(Name alias, Table<UserExtRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("用户扩展信息表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>reactor_demo.user_ext</code> table reference
     */
    public UserExt(String alias) {
        this(DSL.name(alias), USER_EXT);
    }

    /**
     * Create an aliased <code>reactor_demo.user_ext</code> table reference
     */
    public UserExt(Name alias) {
        this(alias, USER_EXT);
    }

    /**
     * Create a <code>reactor_demo.user_ext</code> table reference
     */
    public UserExt() {
        this(DSL.name("user_ext"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ReactorDemo.REACTOR_DEMO;
    }

    @Override
    public Identity<UserExtRecord, Long> getIdentity() {
        return (Identity<UserExtRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserExtRecord> getPrimaryKey() {
        return Keys.KEY_USER_EXT_PRIMARY;
    }

    @Override
    public List<UniqueKey<UserExtRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_USER_EXT_UK_USER_ID);
    }

    @Override
    public UserExt as(String alias) {
        return new UserExt(DSL.name(alias), this);
    }

    @Override
    public UserExt as(Name alias) {
        return new UserExt(alias, this);
    }

    @Override
    public UserExt as(Table<?> alias) {
        return new UserExt(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserExt rename(String name) {
        return new UserExt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserExt rename(Name name) {
        return new UserExt(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserExt rename(Table<?> name) {
        return new UserExt(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserExt where(Condition condition) {
        return new UserExt(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserExt where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserExt where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserExt where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserExt where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserExt where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserExt where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserExt where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserExt whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserExt whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
